#Convert days,hours and minutes to seconds!!
days = float(input("enter the days : "))
hours = float(input("enter the hours : "))
minutes = float(input("enter the minutes : "))
seconds = float(input("enter the seconds : "))
days = (days * 86400)
hours = (hours * 3600)
minutes = (minutes * 60)
total = (days + hours + minutes + seconds)
print("total : " , total , "seconds")
