#"operations performed on 'a' and 'b' "
import math
first_number = float(input("enter your number1:")) 
second_number = float(input("enter your number2:"))
Sum = (first_number + second_number)
the_difference = (second_number - first_number)
Multiplication = (first_number * second_number)
Quotient = (first_number // second_number)
reminder = (first_number % second_number)
Log = (math.log10(first_number))
power = (first_number ** second_number)
print("power = " , power)
print("log = " , Log)
print("reminder = " , reminder)
print("quotient = " , Quotient)
print("multiplication = " , Multiplication)
print("the_difference = " , the_difference)
print("sum = " , Sum)
